### ISSUE TITLE
Make UI improvements for Secondary information

### ISSUE THREAD

**Issue by chumakova-katerina** [chumakova-katerina/homepage#20]
For better UI add such changes:

- [x] increase the space between lines in the Timeline section (`padding-top: 5px;`)
- [x] change tag for Traveler from `<p>` to `<h3>` and `#787F3D`
- [x] change width and color for page border 
- [x] change text in Skills, Character, Hobbies sections to uppercase
- [x] change text link color to `#A2BC4F`

**Comment by MinervaMG** [comment]
@chumakova-katerina  for page border use `border-width: 0.35em;` and `border-color: #787F3D;`
