### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by chumakova-katerina** [chumakova-katerina/homepage#4]
Скласти вступ, де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MinervaMG** [comment]
Frodo Baggins
 22 SEP 2968   Shire
“All we have to decide is what to do with the time that is given us.”

**Comment by chumakova-katerina** [comment]
intro collected

**Comment by chumakova-katerina** [comment]
FRODO BAGGINS
Hobbiton, Shire
Traveler
https://www.facebook.com/FrodoBagginsss/
https://twitter.com/_frodobaggins" rel="nofollow
