### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by chumakova-katerina** [chumakova-katerina/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо.

**Comment by MinervaMG** [comment]
Shire, Bag End
https://en.wikipedia.org/wiki/Frodo_Baggins
https://www.facebook.com/FrodoBagginsss/
https://twitter.com/_frodobaggins_

**Comment by chumakova-katerina** [comment]
contact information collected
